export const STARTER_DECK_NAME = 'Anglais — démarrage'

export const STARTER_CARDS: { front: string; back: string; explanation?: string }[] = [
  { front: 'Bonjour (le matin)', back: 'Good morning' },
  { front: 'Bonsoir', back: 'Good evening' },
  { front: 'Bonne nuit', back: 'Good night' },
  { front: 'Comment ça va ?', back: 'How are you?' },
  { front: 'Ça va bien, merci', back: 'I’m fine, thank you' },
  { front: 'Enchanté', back: 'Nice to meet you' },
  { front: 'À demain', back: 'See you tomorrow' },
  { front: 'À plus tard', back: 'See you later' },
  { front: 'S’il te plaît', back: 'Please' },
  { front: 'Merci beaucoup', back: 'Thank you very much' },
  { front: 'De rien', back: 'You’re welcome' },
  { front: 'Excuse-moi', back: 'Excuse me' },
  { front: 'Pardon / Désolé', back: 'Sorry' },
  { front: 'Je voudrais…', back: 'I would like…' },
  { front: 'Je ne comprends pas', back: 'I don’t understand' },
  { front: 'Pouvez-vous répéter, s’il vous plaît ?', back: 'Could you repeat that, please?' },
  { front: 'Que signifie ce mot ?', back: 'What does this word mean?' },
  { front: 'Comment on dit … en anglais ?', back: 'How do you say … in English?' },
  { front: 'Parlez-vous français ?', back: 'Do you speak French?' },
  { front: 'Je parle un peu anglais', back: 'I speak a little English' },
  { front: 'J’apprends l’anglais', back: 'I am learning English' },
  { front: 'Peux-tu parler plus lentement ?', back: 'Can you speak more slowly?' },
  { front: 'Un peu', back: 'A little' },
  { front: 'Beaucoup', back: 'A lot' },
  { front: 'Je ne sais pas', back: 'I don’t know' },
  { front: 'Bien sûr', back: 'Of course' },
  { front: 'Pas de problème', back: 'No problem' },
  { front: 'D’accord', back: 'Okay / All right' },
  { front: 'J’ai faim', back: 'I am hungry' },
  { front: 'J’ai soif', back: 'I am thirsty' },
  { front: 'J’ai sommeil', back: 'I am sleepy' },
  { front: 'Je suis fatigué', back: 'I am tired' },
  { front: 'Je suis occupé', back: 'I am busy' },
  { front: 'Je suis en retard', back: 'I am late' },
  { front: 'Quelle heure est-il ?', back: 'What time is it?' },
  { front: 'Aujourd’hui', back: 'Today' },
  { front: 'Demain', back: 'Tomorrow' },
  { front: 'Hier', back: 'Yesterday' },
  { front: 'Maintenant', back: 'Now' },
  { front: 'Plus tard', back: 'Later' },
  { front: 'Où est… ?', back: 'Where is…?' },
  { front: 'Combien ça coûte ?', back: 'How much does it cost?' },
  { front: 'L’addition, s’il vous plaît', back: 'The bill, please' },
  { front: 'Je prends ça', back: 'I’ll take this' },
  { front: 'Un café, s’il vous plaît', back: 'A coffee, please' },
  { front: 'De l’eau, s’il vous plaît', back: 'Some water, please' },
  { front: 'Je cherche les toilettes', back: 'I’m looking for the restroom' },
  { front: 'À gauche', back: 'To the left' },
  { front: 'À droite', back: 'To the right' },
  { front: 'Tout droit', back: 'Straight ahead' },
  { front: 'Près de', back: 'Near' },
  { front: 'Loin de', back: 'Far from' },
  { front: 'J’habite à…', back: 'I live in…' },
  { front: 'Je travaille à…', back: 'I work in…' },
  { front: 'Je vais au travail', back: 'I’m going to work' },
  { front: 'Je rentre à la maison', back: 'I’m going home' },
  { front: 'J’ai besoin d’aide', back: 'I need help' },
  { front: 'Peux-tu m’aider ?', back: 'Can you help me?' },
  { front: 'Qu’est-ce que tu fais ?', back: 'What are you doing?' },
  { front: 'Qu’est-ce que tu penses ?', back: 'What do you think?' },
  { front: 'J’aime ça', back: 'I like this' },
  { front: 'Je n’aime pas ça', back: 'I don’t like this' },
  { front: 'C’est important', back: 'It’s important' },
  { front: 'C’est difficile', back: 'It’s difficult' },
  { front: 'C’est facile', back: 'It’s easy' },
  { front: 'Je suis d’accord', back: 'I agree' },
  { front: 'Je ne suis pas d’accord', back: 'I disagree' },
  { front: 'À mon avis', back: 'In my opinion' },
  { front: 'Par exemple', back: 'For example' },
  { front: 'En fait', back: 'Actually' },
  {
    front: 'Qu’est-ce que tu veux dire ?',
    back: 'What do you mean?',
    explanation: 'Pour demander une clarification.',
  },
  {
    front: 'J’arrive',
    back: 'I’ll be right there',
    explanation: '« Je viens tout de suite ». Pas I arrive.',
  },
  {
    front: 'On y va ?',
    back: 'Shall we go?',
    explanation: 'Suggestion. Plus direct : Let’s go.',
  },
  {
    front: 'Tu as raison',
    back: 'You’re right',
  },
  {
    front: 'Ça dépend',
    back: 'It depends',
  },
  {
    front: 'Je n’ai pas le temps',
    back: 'I don’t have time',
  },
  {
    front: 'Attends une seconde',
    back: 'Wait a second',
    explanation: 'Aussi : Hold on.',
  },
  {
    front: 'Ça te dit ?',
    back: 'Do you feel like it?',
    explanation: 'Pour proposer quelque chose. Aussi : Are you up for it?',
  },
  {
    front: 'Ce n’est pas grave',
    back: 'Don’t worry about it',
    explanation: 'Aussi : It’s okay / It’s no big deal.',
  },
  {
    front: 'Je t’appelle plus tard',
    back: 'I’ll call you later',
  },
  {
    front: 'Au fait',
    back: 'By the way',
    explanation: 'Pour changer de sujet, ou ajouter un détail.',
  },
  {
    front: 'Laisse tomber',
    back: 'Never mind',
    explanation: 'Aussi : Forget it.',
  },
  {
    front: 'Fais attention',
    back: 'Be careful',
  },
  {
    front: 'Je te tiens au courant',
    back: 'I’ll keep you posted',
  },
  {
    front: 'C’est parti',
    back: 'Here we go',
    explanation: 'Aussi : Let’s go, pour démarrer.',
  },
  {
    front: 'Tant pis',
    back: 'Too bad',
    explanation: 'Résignation. Moins fort que « c’est grave ».',
  },
  {
    front: 'Je m’en occupe',
    back: 'I’ll take care of it',
  },
  {
    front: 'Ça fait longtemps',
    back: 'It’s been a while',
  },
  {
    front: 'On dirait que…',
    back: 'It looks like…',
  },
  {
    front: 'Compte sur moi',
    back: 'Count on me',
  },
  { front: 'Fenêtre', back: 'Window' },
  { front: 'Clé', back: 'Key' },
  { front: 'Sac', back: 'Bag' },
  { front: 'Téléphone', back: 'Phone' },
  { front: 'Argent', back: 'Money' },
  { front: 'Voiture', back: 'Car' },
  { front: 'Ami / amie', back: 'Friend' },
  { front: 'Réunion', back: 'Meeting' },
  { front: 'Message', back: 'Message' },
  {
    front: 'Magasin',
    back: 'Store',
    explanation: 'UK : shop. US : store.',
  },
  {
    front: 'Travailler',
    back: 'To work',
    explanation: 'Régulier : work → worked.',
  },
  {
    front: 'Jouer',
    back: 'To play',
    explanation: 'Régulier : play → played.',
  },
  {
    front: 'Écouter',
    back: 'To listen',
    explanation: 'Régulier : listen → listened. On dit listen to.',
  },
  {
    front: 'Regarder',
    back: 'To watch',
    explanation: 'Régulier : watch → watched. Look = jeter un coup d’œil.',
  },
  {
    front: 'Demander',
    back: 'To ask',
    explanation: 'Régulier : ask → asked.',
  },
  {
    front: 'Commencer',
    back: 'To start',
    explanation: 'Régulier : start → started. Aussi : to begin (irrégulier).',
  },
  {
    front: 'Essayer',
    back: 'To try',
    explanation: 'Régulier : try → tried (y → ied).',
  },
  {
    front: 'Utiliser',
    back: 'To use',
    explanation: 'Régulier : use → used.',
  },
  {
    front: 'Décider',
    back: 'To decide',
    explanation: 'Régulier : decide → decided.',
  },
  {
    front: 'Se souvenir de',
    back: 'To remember',
    explanation: 'Régulier : remember → remembered.',
  },
]
