/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Cards: () => import('#controllers/cards_controller'),
  Decks: () => import('#controllers/decks_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Study: () => import('#controllers/study_controller'),
}
