/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CardSchema extends BaseModel {
  static $columns = ['back', 'createdAt', 'deckId', 'dueAt', 'ease', 'explanation', 'firstReviewedAt', 'flagged', 'front', 'id', 'interval', 'lapses', 'lastReviewedAt', 'repetitions', 'updatedAt'] as const
  $columns = CardSchema.$columns
  @column()
  declare back: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deckId: number
  @column.dateTime()
  declare dueAt: DateTime
  @column()
  declare ease: number
  @column()
  declare explanation: string | null
  @column.dateTime()
  declare firstReviewedAt: DateTime | null
  @column()
  declare flagged: boolean
  @column()
  declare front: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare interval: number
  @column()
  declare lapses: number
  @column.dateTime()
  declare lastReviewedAt: DateTime | null
  @column()
  declare repetitions: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DeckSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'newCardsPerDay', 'updatedAt', 'userId'] as const
  $columns = DeckSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare newCardsPerDay: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
